import type { Metadata } from 'next';
import { Geist, Geist_Mono, JetBrains_Mono, Montserrat, Poppins } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { Providers } from '@/providers/auth';
import { Toaster } from '@/components/ui/sonner';

// Fuentes principales
const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

// Fuentes adicionales
const poppins = Poppins({ variable: '--font-poppins', subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });
const jetbrains = JetBrains_Mono({ variable: '--font-jetbrains', subsets: ['latin'] });
const montserrat = Montserrat({ variable: '--font-montserrat', subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });

export const metadata: Metadata = { title: 'Sistema de Certificados', description: 'Generated by create next app' };

const RootLayout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable}${geistMono.variable}${poppins.variable}${jetbrains.variable}${montserrat.variable}antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {/* <AuthProvider session={session}>{children}</AuthProvider> */}
          <Providers>{children}</Providers>
          <Toaster richColors position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
